game.resources = [
    {name: "bg", type:"image", src: "data/img/Game-grass.png"},
    {name: "bgstatic", type:"image", src: "data/img/Game-bg.png"},
    {name: "rival1", type: "image", src: "data/img/horse_510x468_pink.png" },
    {name: "rival2", type: "image", src: "data/img/horse_510x468_red.png" },
    {name: "rival3", type: "image", src: "data/img/horse_510x468_purple.png" },
    {name: "player", type:"image", src: "data/img/horse_510x468.png"},
    {name: "fence", type:"image", src: "data/img/Game-fence.png"},
    {name: "sky", type:"image", src: "data/img/sky.png"},
    {name: "grass1", type:"image", src: "data/img/tuft-1.png"},
    {name: "grass2", type:"image", src: "data/img/tuft-2.png"},
    {name: "crash", type:"image", src: "data/img/crash-comic-text-bubble.jpg"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "splash", type:"image", src: "data/img/splash-screen.png"},
    {name: "gameoverbg", type:"image", src: "data/img/entryScreen.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "grumpybird", type:"image", src: "data/img/grumpybird.png"},
    {name: "light", type:"image", src: "data/img/office_assets_light.png"},
    {name: "cabinet", type:"image", src: "data/img/office_assets_kiwi_cabinet.png"},
    {name: "desk_sml", type:"image", src: "data/img/desk-sml-2.png"},
    {name: "desk_lrg", type:"image", src: "data/img/desk-lrg-2.png"},
    {name: "try_again", type: "image", src: "data/img/try_again_button.png"},
    {name: "enter_comp_button", type: "image", src: "data/img/enter_comp_button.png"},
    {name: "best_score_background", type: "image", src: "data/img/best_score_button_container.png"},
    {name: "shapesdef", type:"json", src: "data/json/kiwi_trace.json"}
];
